export AR = ar
export CC = gcc
export CC_FLAGS = -Wall -fno-rtti -fno-exceptions -O2 -static-libgcc
export MKDIR = mkdir -p

export OBJDIR = obj
TICKLE = tickle

all: $(OBJDIR)/$(TICKLE)
	$(MKDIR) $(OBJDIR)
	$(MAKE) -C src

clean:
	rm -fR $(OBJDIR)

.PHONY: all $(OBJDIR)/$(TICKLE)

